# Generated by Django 5.2.3 on 2025-06-26 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_item_image_url_alter_item_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='type',
            field=models.CharField(choices=[('bread', 'Bread'), ('pastries', 'Pastries'), ('cake', 'Cake'), ('misc', 'Miscellaneous')], max_length=20),
        ),
    ]
